language: python
python:
- '3.6'
env:
  global:
  - GH_USER=junshoong
  - GH_REPO=blog
  - secure: cDHbeN2pbsk8+UG27IMj9ZyVzEtbnt8T/x35fAcTE517eG9iPk++Z5gLn6+AujaBYUNa7eAK77K46Q6LfBKcFCu4EEqQfpi8ot1n9utGxkQdMQhcrendBYl9we34WELIks0yu6r75OzGgBAKbaeeBC/v4/Y3+WGF5q8YOpp3LBR7TMVFdg7Qc8Kqg3EXo8a+Od2z9B3dYyNaxW7oDHfNbI2hRJ3TGauZo6zwpegDMPqPKhZb02vzXqH04I+ey9FzP6EnjAHmG/lBfM11x0r7udOlXZI3V6jHr+8H83Ebn9Uegjs7tTmr0d5jYR9k7Q4U9pRGmA8JXUxGP7jUGwp2v8Md3qmYS4NivN5hfbaHsmAy2xWUYSbsBcJqn1CQAsbsehe3mqmN8KcAd/C7UxNzQzCy7Bxq3jOAtD7Nq5pqBloEJ3PB1a/8nFr/9fD+CvWXIdjSjPTG7VJdXVFU5UW+5RMUv0JLx3cFqALbWNZtJCqwxjAqZDn/m3pYE7FypxOwWxJc0LQaixbKzGOv8W3RwBxL1pp6gyoPcbTCAi8B0sagPxZasIsNGsYTY7scQDADttfo6RIhho3Pn4YllGl1fPgeKmOgSorBGdNrshBHJoTvEgWBc7pV7976Nk+lfGWqhCtJHW6e+AilBi9vKQvK3b6yXZGGAiTgyMRaVMwoPIA=

before_install:
- git config --global user.email "junshoong@gmail.com"
- git config --global user.name "Junshoog"
- git clone -b generator --quiet --recursive https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git generator
- cd generator

install:
- pip install -r requirements.txt -q

before_script:
- git clone -b gh-pages --depth 1 --quiet https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git output
- cd content
- rm -rf posts
- git clone -b post --depth 1 --quiet https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git posts
- cd ..
- git add -A
- git commit -m "Blog Contents updated by Travis-CI"
- git push https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git generator --quiet

script:
- make publish

after_success:
- cd output
- git add -A
- git commit -m "Github Pages updated by Travis-CI."
- git push https://${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git gh-pages --quiet

branches:
  only:
  - post
